# Линейная алгебра, математический анализ

# Задание 1
#### Даны матрицы:
$$
A = \begin{pmatrix}
-2 & -4 \\
3 & 5 \\
-1 & 0
\end{pmatrix}, \quad
B = \begin{pmatrix}
1 & 2 & 7 \\
-3 & -4 & 0 \\
5 & 2 & 1
\end{pmatrix},
\quad
C = \begin{pmatrix}
6 & -3 & 9 \\
4 & -5 & 2 \\
8 & 1 & 5
\end{pmatrix}.
$$

Посчитать  $D = A^{T}C-2A^{T}B^{T}$

---
## Решение:
### 1. переворачиваем матрицы A и B
$$
A^{T} = \begin{pmatrix}
-2 & 3 & -1 \\
-4 & 5 & 0 \\
\end{pmatrix}, \quad
B^{T} = \begin{pmatrix}
1 & -3 & 5 \\
2 & -4 & 2 \\
7 & 0 & 1
\end{pmatrix}
$$

### 2. перемножаем  эти матрицы $A^{T}*B^{T}$
2х3 и 3х3 -> должна получиться матрица 2х3

берем первую строку из матрицы А, умножаем элементы на первый столбец В и все складываем = это элемент j11
$j11 = -2*1 + 3*2 + -1*7 = -3$

потом умножаем (и складываем) первую строку матрицы А на второй столбец матрицы В
$j12 = -2*-3 + 3*-4 + -1*0 = -6$

и первую строку матрицы А умножить на третий столбец матрицы В
$j13 = -2*5 + 3*2 + -1*1 = -5$

то же самое для второй строки из матрицы А, чтобы заполнить вторую строку в целевой матрице

$j21 = -4*1 + 5*2 + 0*7 = 6$

$j22 = -4*-3 + 5*-4 + 0*0 = -8$

$j23 = -4*5 + 5*2 + 0*1 = -10$

Итого $A^{T}*B^{T}$  = $\begin{pmatrix}-3 & -6 & -5 \\6 & -8 & -10 \\\end{pmatrix}$

### 3. умножаем матрицу на -2
каждый элемент матрицы умножаем на -2

Итого $-2*A^{T}*B^{T}$  = $\begin{pmatrix}6 & 12 & 10 \\-12 & 16 & 20 \\\end{pmatrix}$

### 4. перемножаем $A^{T}*С$

$$
A^{T} = \begin{pmatrix}
-2 & 3 & -1 \\
-4 & 5 & 0 \\
\end{pmatrix}\quad* \quad
C = \begin{pmatrix}
6 & -3 & 9 \\
4 & -5 & 2 \\
8 & 1 & 5
\end{pmatrix}
$$

первую строчку А на все столбцы С
вторую строчку А на все столбцы С

Итого $A^{T}*С$ = $\begin{pmatrix}-8 & -10 & -17 \\-4 & -13 & -26 \\\end{pmatrix}$


### 5. осталось сложить 2 матрицы
т.к. на -2 уже умножили выше ^

$\begin{pmatrix}6 & 12 & 10 \\-12 & 16 & 20 \\\end{pmatrix}$ + $\begin{pmatrix}-8 & -10 & -17 \\-4 & -13 & -26 \\\end{pmatrix}$

складываем по элементно

$\begin{pmatrix}6+-8 & 12+-10 & 10+-17 \\-12+-4 & 16+-13 & 20+-26 \\\end{pmatrix}$


#### Ответ:  D = $\begin{pmatrix}-2 & 2 & -7 \\-16 & 3 & -6 \\\end{pmatrix}$

---


# Задание 2
Найти значения.

$$
3 * \begin{pmatrix}
x & 2 & 3 \\
-1 & y & 4 \\
\end{pmatrix} \quad + \quad
2 * \begin{pmatrix}
1 & 2 & -5 \\
2 & -6 & z \\
\end{pmatrix},
\quad = \quad
\begin{pmatrix}
8 & v & -1 \\
1 & 6 & 4 \\
\end{pmatrix}.
$$



## Решение
Перемножаем матрицы
$$
\begin{pmatrix}
3x & 6 & 9 \\
-3 & 3y & 12 \\
\end{pmatrix} \quad + \quad
\begin{pmatrix}
2 & 4 & -10 \\
4 & -12 & 2z \\
\end{pmatrix},
\quad = \quad
\begin{pmatrix}
8 & v & -1 \\
1 & 6 & 4 \\
\end{pmatrix}.
$$

складываем слева матрицы поэлементно
$$
\begin{pmatrix}
3x+2 & 6+4 & 9+-10 \\
-3+4 & 3y+-12 & 12+2z \\
\end{pmatrix} \quad = \quad
\begin{pmatrix}
8 & v & -1 \\
1 & 6 & 4 \\
\end{pmatrix}.
$$

получается:

$$
\begin{pmatrix}
3x+2 & 10 & -1 \\
1 & 3y-12 & 12+2z \\
\end{pmatrix} \quad = \quad
\begin{pmatrix}
8 & v & -1 \\
1 & 6 & 4 \\
\end{pmatrix}.
$$

теперь каждый элемент слева приравнивается к такому же из правой матрицы

3x + 2 = 8
10 = v
-1 = -1
1 = 1
3y - 12 = 6
12 + 2z = 4

решение уравнений:
x = 6 / 3 = 2
v = 10
y = 18 / 3 = 6
z = -8 / 2 = -4

---

---

---

# Задание 3

При каких значениях p, q матрица имеет ранг 1

$$
\begin{pmatrix}
1 & 2 & 3 \\
3 & 6 & p \\
5 & 10 & q \\
\end{pmatrix}
$$

значения в первых двух столбцах пропорциональны как в первой строке
тогда
p = 3 * 3 = 9
q = 5 * 3 = 15

в этом случае вторая и третья строка в матрице зависят от логики первой строки
получается, что независимых строк - только первая, значит ранг матрицы = 1

---


---

---

# Задание 4

в стандартном базисе $\mathbb{R}^2$ даны 3 вектора:
$a_1=(2,-5)^T,\quad a_2=(-1,3)^T, \quad x=(1,-4)^T$


---

---
---


# Задание 5
малоранговая аппроксимация матрицы

## Решение
---
### шаг 1
генерим случайную квадратную матрицу  $A \quad принадлежит \quad \mathbb{R}^2$:



In [27]:
import numpy as np
n = 5 # строки и столбцы для матрицы

matrix_A = np.random.randint(-10,10,(n,n))
print(matrix_A)

[[ -8   0   4  -9   2]
 [-10   1   9  -1   4]
 [  7  -2  -5 -10 -10]
 [  4   2   0  -2  -2]
 [  7   3  -8   2  -9]]


---
### шаг 2
теперь надо умножить исходную матрицу на ее транспонированный вариант

In [12]:
AtA = matrix_A.T @ matrix_A
print(AtA)

[[ 83   0  17   4  56]
 [  0 176 -18 -35  -1]
 [ 17 -18  85  44  14]
 [  4 -35  44  80 -36]
 [ 56  -1  14 -36 132]]


---
### шаг 3
теперь надо вычислить собственные векторы и собственные числа

In [17]:
# Calculate eigenvalues (w) and eigenvectors (v)
eigenvalues, V_vectors = np.linalg.eigh(AtA)

# Sort them in descending order (SVD convention)
idx = eigenvalues.argsort()[::-1]
eigenvalues = eigenvalues[idx]
V_vectors = V_vectors[:, idx]
print(f'собственные значения \n{eigenvalues}')
print('-'*15)
print(f'собственные вектора \n{V_vectors}')


собственные значения 
[198.07130917 176.66622529 111.85324118  48.64795378  20.76127057]
---------------
собственные вектора 
[[-0.03503491 -0.5121459   0.23259251  0.76218827 -0.31851044]
 [-0.85398187  0.18862437  0.47297622 -0.01247463  0.10617765]
 [ 0.26641999 -0.19706159  0.64893761 -0.50947429 -0.45771503]
 [ 0.40671022  0.12076764  0.53641396  0.2260257   0.69366737]
 [-0.18191952 -0.80542494 -0.11547406 -0.32903154  0.44339591]]


---
### шаг 4
дальше высчитываются квадратные корни от собственных значений, типа как коэф влияния или важности векторов. Чем больше сингулярное значение, тем важней этот вектор

In [37]:
# Square root of eigenvalues = Singular Values
s = np.sqrt(np.maximum(eigenvalues, 0))
Sigma = np.diag(s)
print(f'сингулярные значения как корни из собственных чисел \nотсортированные от большего к меньшему \n{s}')
print('-'*15)
print(f' \n{Sigma}')

сингулярные значения как корни из собственных чисел 
отсортированные от большего к меньшему 
[14.07378091 13.29158475 10.57606927  6.97480851  4.55645373]
---------------
 
[[14.07378091  0.          0.          0.          0.        ]
 [ 0.         13.29158475  0.          0.          0.        ]
 [ 0.          0.         10.57606927  0.          0.        ]
 [ 0.          0.          0.          6.97480851  0.        ]
 [ 0.          0.          0.          0.          4.55645373]]


---
### шаг 5

построить матрицу **$V^H$** и матрицу **U**.
Где **$V^H$** описывает поворот к осям
**U** описывает как данные выглядят после трансформации

In [24]:
# V-Hermitian is just the transpose of our V_vectors
Vh = V_vectors.T

# U is calculated by projected A onto V and normalizing by Sigma
# Or more simply, use the built-in function to get U directly:
U, s_internal, Vh_internal = np.linalg.svd(matrix_A)
print(f'Vh:\n{Vh_internal}')
print('-'*15)
print(f'U:\n{U}')
print('-'*15)
print(f's_internal:\n{s_internal}')
print('-'*15)

Vh:
[[ 0.03503491  0.85398187 -0.26641999 -0.40671022  0.18191952]
 [ 0.5121459  -0.18862437  0.19706159 -0.12076764  0.80542494]
 [ 0.23259251  0.47297622  0.64893761  0.53641396 -0.11547406]
 [ 0.76218827 -0.01247463 -0.50947429  0.2260257  -0.32903154]
 [-0.31851044  0.10617765 -0.45771503  0.69366737  0.44339591]]
---------------
U:
[[ 0.49304276  0.22508207  0.18804441 -0.42414146 -0.70070694]
 [ 0.12800793 -0.60153025  0.783169    0.04204094  0.08157326]
 [ 0.18828386  0.73822628  0.48627939  0.22785861  0.36219326]
 [ 0.12003654 -0.03871524 -0.04735841  0.87284956 -0.46902366]
 [ 0.8310615  -0.20254012 -0.33552221  0.06745874  0.38882958]]
---------------
s_internal:
[14.07378091 13.29158475 10.57606927  6.97480851  4.55645373]
---------------


---
### Пример уменьшения этой матрицы до 5х2


In [40]:
# Разложение на собств числа, векторы
U, s, Vh = np.linalg.svd(matrix_A)

# определяем ранг матрицы 2, чтобы получить 2 самые важные вектора и игнорировать остальные
k = 2

# 4. уменьшаем матрицу до размерности 5x2. т.е. новая матрица U 5х2 типа как новые координаты для исходной матрицы
# U страновится (5, 2), s -> (2,), Vh -> (2, 5)
U_k = U[:, :k]
s_k = s[:k]
Vh_k = Vh[:k, :]

# 5. восстанавливаем матрицу из сжатой матрицы, посмотреть насколько близко восстановится к исходным значениям

A_compressed = U_k @ np.diag(s_k) @ Vh_k

print(f'исходная матрица: \n{matrix_A}')
print('-'*15)
print(f'сжатая матрица: \n{A_compressed.round(3)}')

исходная матрица: 
[[ -8   0   4  -9   2]
 [-10   1   9  -1   4]
 [  7  -2  -5 -10 -10]
 [  4   2   0  -2  -2]
 [  7   3  -8   2  -9]]
---------------
сжатая матрица: 
[[ -7.038  -1.064   5.486  -8.78    1.648]
 [ -9.228  -0.455   7.468  -1.934   6.483]
 [  6.57   -0.81   -5.651 -10.175  -9.83 ]
 [  2.202  -0.088  -1.839  -1.539  -2.45 ]
 [  9.238   0.388  -7.497   1.249  -6.801]]


---
и проверка качества уменьшения матрицы


In [41]:
total_energy = np.sum(s**2)
captured_energy = np.sum(s_k**2)
accuracy = (captured_energy / total_energy) * 100
print(f'точность: { accuracy:.3f}%')

точность: 94.584%


---
### пример расчетов для размерности n >= 100

тут еще разобраться как это работает



In [54]:
import numpy as np

n = 201
matrix_large_A = np.random.randint(-100,100,(n,n))

# 1. Get the singular values (this is the most "expensive" part)
U, s, Vh = np.linalg.svd(matrix_large_A)

# 2. Calculate the energy of each singular value
energies = s**2

# 3. Calculate the cumulative percentage of energy
# This creates an array: [energy1, energy1+2, energy1+2+3, ...]
cumulative_energy = np.cumsum(energies)
total_energy = np.sum(energies)
accuracy_levels = (cumulative_energy / total_energy) * 100

# 4. Find the first index where accuracy >= 95.5%
# np.argmax returns the first index where the condition is True
k = np.argmax(accuracy_levels > 95.5) + 1 # +1 потому что первый индекс нулевой

print(f"To reach 95.5% accuracy, use k = {k}")
print(f"Actual accuracy at k={k}: {accuracy_levels[k-1]:.2f}%")

To reach 95.5% accuracy, use k = 147
Actual accuracy at k=147: 95.65%


---

---

---



# Задание 1

Посчитать градиент функции:
$f(x)=x_{1}^3 - 2x_{1}x_{2} + x_{2}^2 - 3x_{1} - 2x_{2}$

Найти критические точки $x_{c}$, такие что $\nabla f(x_{c})=0$


---

## Решение
---
### шаг 1

посчитать частные производные, чтобы понять скорость изменения по одной оси.
по x1:
$\frac{\partial f}{\partial x_1} = 3x_1^2 - 2x_2 - 3$

по x2: $\frac{\partial f}{\partial x_2} = -2x_1 + 2x_2 - 2$

получилась матрица, чтобы посчитать градиент:
$\nabla f(x) = \begin{pmatrix} 3x_1^2 - 2x_2 - 3 \\ -2x_1 + 2x_2 - 2 \end{pmatrix}$




---
### шаг 2

приравниваем уравнения к нулю, чтобы найти точку в которой производные равны нулю. т.е. когда векторы равны нулю, значит мы находимся в минимальной точке (а может в максимальной, не понял тут как отличить минимум от максимума, чат говорит, что надо считать вторую производную, если знак будет "+", то это ямка, если "-", то горка)

$\text{(уравнение 1)}\quad 3x_1^2 - 2x_2 - 3 = 0$

$\text{(уравнение 2)}\quad -2x_1 + 2x_2 - 2 = 0$

Решаем систему уравнений:

$-2x_1 + 2x_2 - 2 = 0 \quad \text{->} \quad 2x_2 = 2x_1 + 2 \quad \text{->} \quad x_2 = x_1 + 1$

Подставляем это в первое уравнение:
$3x_1^2 - 2(x_1 + 1) - 3 = 0\quad \text{->} \quad 3x_1^2 - 2x_1 - 5 = 0$

решаем квадратное уравнение:
  $x_1 = \frac{-b \pm \sqrt{(b)^2 - 4 \cdot a \cdot c}}{2 \cdot a}$


$x_1 = \frac{2 \pm \sqrt{(-2)^2 - 4 \cdot 3 \cdot (-5)}}{2 \cdot 3}$

$x_1 = \frac{2 \pm \sqrt{4 + 60}}{6}$

$x_1 = \frac{2 \pm 8}{6} \quad$  где $\quad x_1 = \frac{5}{3}$ или $\quad x_1 = -1$

  Находим x2:
  $x_2 = \frac{5}{3} + 1 = \frac{5}{3} + \frac{3}{3} = \frac{8}{3}\quad$
  или $\quad x_2 = -1 + 1 = 0$

---
### шаг 3
Проверяем градиент на 0 в полученных точках

$\mathbf{x}_c = \left(\frac{5}{3}, \frac{8}{3}\right) \quad \text{и} \quad \mathbf{x}_c =  (-1, 0)$

$\nabla f(x) = \begin{pmatrix} 3x_1^2 - 2x_2 - 3 \\ -2x_1 + 2x_2 - 2 \end{pmatrix}$

---

In [6]:
# Method 2: Analytical solution using sympy
import sympy as sp

def gradient_equation():
    x1, x2 = sp.symbols('x1 x2')
    f = x1**3 - 2*x1*x2 + x2**2 - 3*x1 - 2*x2

    # градиент
    gradient = [sp.diff(f, x1), sp.diff(f, x2)]

    # приравнять к нулю
    critical_points = sp.solve(gradient, (x1, x2))

    return critical_points, gradient

if __name__ == "__main__":
    # символ частной производной \u2202
    points, gradient_values = gradient_equation()
    print("Решение")
    print(f"Gradient values: \u2202f/\u2202x1 = {gradient_values[0]}, \u2202f/\u2202x2 = {gradient_values[1]}")
    print(f"Critical points: {points}")

Решение
Gradient values: ∂f/∂x1 = 3*x1**2 - 2*x2 - 3, ∂f/∂x2 = -2*x1 + 2*x2 - 2
Critical points: [(-1, 0), (5/3, 8/3)]
