# Я художник, я так вижу, визуализация данных в питоне

# I. Numpy

### Импортируйте NumPy

In [2]:
import numpy as np

### Создайте одномерный массив размера 10, заполненный нулями и пятым элемент равным 1. Трансформируйте в двумерный массив.

In [6]:
d1_array = np.zeros(10)
print(d1_array)
d1_array[4] = 1
print(d1_array)
d2_array = np.reshape(d1_array,(2,5))
print(d2_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


### Создайте одномерный массив со значениями от 10 до 49 и разверните его (первый элемент становится последним). Найдите в нем все четные элементы.

In [14]:
my_array = np.arange(start=10, stop=50, step=1)
print(my_array)

reversed_array = my_array[::-1]
print(f' reversed array:\n{my_array}')

even_array = reversed_array[reversed_array % 2 == 0]
print(f' even array:\n{even_array}')

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
 reversed array:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
 even array:
[48 46 44 42 40 38 36 34 32 30 28 26 24 22 20 18 16 14 12 10]


### Создайте двумерный массив 3x3 со значениями от 0 до 8

In [17]:
my_array = np.arange(0,9,1).reshape(3,3)
print(my_array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


### Создайте массив 4x3x2 со случайными значениями. Найти его минимум и максимум.

In [22]:
my_array = np.random.random((4,3,2))
# print(my_array)

print(np.min(my_array))
print(np.max(my_array))



[[[0.85395004 0.27441912]
  [0.60244328 0.68680177]
  [0.47327167 0.33655866]]

 [[0.61975842 0.78988542]
  [0.42102217 0.01950179]
  [0.90754084 0.02567939]]

 [[0.25526462 0.50189953]
  [0.52388125 0.74048149]
  [0.91396033 0.90991331]]

 [[0.33172231 0.99084317]
  [0.52537058 0.37260939]
  [0.01259922 0.37260257]]]
0.990843168078448
0.012599216542524494


### Создайте два двумерных массива размерами 6x4 и 4x3 и произведите их матричное умножение. 

In [25]:
array_1 = np.random.random((6,4))
array_2 = np.random.random((4,3))

array_3 = array_1.dot(array_2)
print(np.shape(array_3))
print(array_3)


[[1.12171196 0.39235021 1.13294224]
 [0.95931713 0.39308718 1.09926013]
 [0.82145324 0.4316118  0.86758728]
 [1.85393367 0.71646156 1.96410388]
 [0.88189633 0.18390845 0.89273393]
 [1.4761123  0.41760853 1.65006811]]
(6, 3)


### Создайте случайный двумерный массив 7x7, найти у него среднее и стандартное оклонение. Нормализуйте этот массив.

In [28]:
# my_array = np.random.random((7,7))
my_array = np.random.randint(0,100,(7,7))
print(my_array)

sredn = np.mean(my_array)
print(sredn)
std =  np.std(my_array)
print(std)

[[47 34 72 44 83 81 22]
 [25 98 44 68 14  4 99]
 [43 47 78 78  8 31 37]
 [67 11 26 56 73 68  7]
 [11 40 29 60 32 42 65]
 [38 26 18 95  0  1 26]
 [31  1 85 11 41 47 93]]
44.02040816326531
28.385458907412843


# II. Pandas

### Импортируйте: pandas, matplotlib, seaborn

In [31]:
import pandas as pd
import matplotlib as plt
import seaborn as sns



ModuleNotFoundError: No module named 'pandas'

### Загрузите датасет Tips из набора датасетов seaborn

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на первые 5 строчек

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте сколько всего строчек и колонок в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Проверьте есть ли пропуски в данных

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Посмотрите на распределение числовых признаков

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите максимальное значение 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Найдите количество курящих людей

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Узнайте какой средний 'total_bill' в зависимости от 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Отберите строчки с 'total_bill' больше медианы и узнайте какой средний 'tip' в зависимости от 'sex'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Преобразуйте признак 'smoker' в бинарный (0-No, 1-Yes)

In [ ]:
# ВАШ КОД ЗДЕСЬ

# III. Visualization

### Постройте гистограмму распределения признака 'total_bill'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте scatterplot, представляющий взаимосвязь между признаками 'total_bill' и 'tip'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте pairplot

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте график взаимосвязи между признаками 'total_bill' и 'day'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте две гистограммы распределения признака 'tip' в зависимости от категорий 'time'

In [ ]:
# ВАШ КОД ЗДЕСЬ

### Постройте два графика scatterplot, представляющих взаимосвязь между признаками 'total_bill' и 'tip' один для Male, другой для Female и раскрасьте точки в зависимоти от признака 'smoker'

In [ ]:
# ВАШ КОД ЗДЕСЬ

## Сделайте выводы по анализу датасета и построенным графикам. По желанию можете продолжить анализ данных и также отразить это в выводах.

In [ ]:
# ВАШ КОД ЗДЕСЬ